package fr.hoenheimsports.model.builder;

import fr.hoenheimsports.model.PhoneNumber;
import fr.hoenheimsports.model.Referee;
import org.junit.jupiter.api.Test;

import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

class RefereeBuilderTest {
    @Test
    public void testRefereeBuilder() {
        RefereeBuilder refereeBuilder = new RefereeBuilder();
        UUID expectedId = UUID.randomUUID();
        String expectedName = "John Doe";
        String expectedPhoneNumber = "1234567890";

        Referee referee = refereeBuilder
                .withId(expectedId)
                .withName(expectedName)
                .withPhoneNumber(phoneNumberBuilder -> phoneNumberBuilder.withPhoneNumber(expectedPhoneNumber))
                .build();

        assertEquals(expectedId, referee.id());
        assertEquals(expectedName, referee.name());
        assertNotNull(referee.phoneNumber());
        assertEquals(expectedPhoneNumber, referee.phoneNumber().phoneNumber());
    }

    @Test
    public void testRefereeBuilderWithAutoGeneratedId() {
        RefereeBuilder refereeBuilder = new RefereeBuilder();
        String expectedName = "John Doe";
        String expectedPhoneNumber = "1234567890";

        Referee referee = refereeBuilder
                .withName(expectedName)
                .withPhoneNumber(phoneNumberBuilder -> phoneNumberBuilder.withPhoneNumber(expectedPhoneNumber))
                .build();

        assertNotNull(referee.id());
        assertEquals(expectedName, referee.name());
        assertNotNull(referee.phoneNumber());
        assertEquals(expectedPhoneNumber, referee.phoneNumber().phoneNumber());
    }

    @Test
    public void testRefereeBuilderWithPhoneNumberObject() {
        RefereeBuilder refereeBuilder = new RefereeBuilder();
        UUID expectedId = UUID.randomUUID();
        String expectedName = "John Doe";
        PhoneNumber expectedPhoneNumber = new PhoneNumber("1234567890");

        Referee referee = refereeBuilder
                .withId(expectedId)
                .withName(expectedName)
                .withPhoneNumber(expectedPhoneNumber)
                .build();

        assertEquals(expectedId, referee.id());
        assertEquals(expectedName, referee.name());
        assertNotNull(referee.phoneNumber());
        assertEquals(expectedPhoneNumber, referee.phoneNumber());
    }

    @Test
    public void testRefereeBuilderWithPhoneNumberObjectAndAutoGeneratedId() {
        RefereeBuilder refereeBuilder = new RefereeBuilder();
        String expectedName = "John Doe";
        PhoneNumber expectedPhoneNumber = new PhoneNumber("1234567890");

        Referee referee = refereeBuilder
                .withName(expectedName)
                .withPhoneNumber(expectedPhoneNumber)
                .build();

        assertNotNull(referee.id());
        assertEquals(expectedName, referee.name());
        assertNotNull(referee.phoneNumber());
        assertEquals(expectedPhoneNumber, referee.phoneNumber());
    }
}